/** 中文文案集中管理（开发规划 5.2，为多语言预留）。 */
export const ZH = {
  app: {
    name: 'Recall',
    subtitle: 'AI 智能错题本',
  },
  nav: {
    home: '首页',
    import: '录入',
    mistakes: '错题本',
    review: '复习',
    dashboard: '看板',
    chat: 'AI 对话',
    help: '帮助',
    settings: '设置',
  },
  status: {
    pending: '未开始',
    wrong: '未掌握',
    fixing: '待巩固',
    mastered: '已掌握',
  },
  statusColors: {
    pending: '灰',
    wrong: '红',
    fixing: '橙',
    mastered: '绿',
  },
  errorTypes: {
    knowledge: '知识性错误',
    logic: '逻辑错误',
    reading: '审题错误',
    calculation: '计算错误',
    concept: '概念混淆',
    careless: '粗心',
    other: '其他',
  },
  source: {
    image: '识图录入',
    text: '文本录入',
    chat: '对话录入',
  },
  common: {
    cancel: '取消',
    confirm: '确认',
    save: '保存',
    edit: '编辑',
    delete: '删除',
    retry: '重试',
    loading: '加载中…',
    empty: '暂无数据',
    back: '返回',
    search: '搜索',
    searchPlaceholder: '搜索题干、知识点、错因…',
    clearFilters: '清除筛选条件',
    noResult: '没有找到相关错题',
    copied: '已复制',
  },
  errors: {
    network: '网络异常，请检查网络后重试',
    aiBusy: 'AI 服务暂时繁忙，请稍后重试',
    uploadFormat: '仅支持 JPG / PNG / WebP / HEIC 图片',
    uploadTooLarge: '图片过大，请压缩后上传（≤10MB）',
    ocrFailed: '未识别到清晰文字，请重拍或换图；可改用文本录入',
    emptyQuestion: '请输入题干内容',
    exportFailed: '导出失败，请重试；超过 200 题请分批导出',
    gradingUnavailable: '批改服务暂不可用，题目已保存，稍后可在列表中重试批改',
  },
  emptyStates: {
    noNotebookTitle: '还没有错题本',
    noNotebookDesc: '三步开始：录入 → 归档 → 复习',
    noNotebookAction: '新建错题本',
    emptyNotebookTitle: '错题本还是空的',
    emptyNotebookEntries: {
      chat: { title: 'AI 对话', desc: '提问时一键加入错题本' },
      image: { title: '识图录入', desc: '拍照 / 截图 / 粘贴，AI 自动拆题' },
      text: { title: '文本录入', desc: '粘贴题干，AI 补全归档字段' },
    },
    dashboardTitle: '暂无数据，先录入一道错题吧',
    dashboardAction: '去录入',
    dashboardSecondary: '去 AI 答疑',
    noConversation: '还没有对话',
    startChat: '开始提问',
  },
  shortcuts: {
    '/': '聚焦全局搜索',
    'Ctrl+E': '打开录入页',
    'Ctrl+Enter': 'AI 答疑发送消息',
    'Alt+R': '从首页开始复习',
    Esc: '关闭弹窗 / 气泡 / 展开区',
  },
} as const

export type MistakeStatus = keyof typeof ZH.status
export type ErrorType = keyof typeof ZH.errorTypes
